### ISSUE TITLE
InvalidOptions: Failed to parse "headers.cache-control.maxAge" option. Value "6 months" is invalid.

### ISSUE THREAD

**Issue by Jubijub** [yvele/poosh#2]
```
Matched files: 0 (0 B), 0%.
Uploaded files: 0 (0 B)
Deleted remote files: 0 (0 B)
0 creations, 0 updates, 0 deletions, 0 skips.
Elapsed time: 2 seconds.
InvalidOptions: Failed to parse "headers.cache-control.maxAge" option. Value "6 months" is invalid.
    at parseMs (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-common\lib\options\parseMs.js:37:11)
    at parseSeconds (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-common\lib\options\parseSeconds.js:35:34)
    at addMaxAgeDirective (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-core\lib\pipeline\headers\appendCacheControl.js:26:45)
    at appendCacheControl (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-core\lib\pipeline\headers\appendCacheControl.js:54:3)
    at appendHeaders (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-core\lib\pipeline\appendHeaders.js:46:38)
    at Pipeline._callee$ (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-core\lib\pipeline\Pipeline.js:104:45)
    at tryCatch (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\babel-regenerator-runtime\runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\babel-regenerator-runtime\runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\babel-regenerator-runtime\runtime.js:94:21)
    at step (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-core\lib\pipeline\Pipeline.js:55:191)
    at C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\poosh-core\lib\pipeline\Pipeline.js:55:368
    at run (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\core-js\modules\es6.promise.js:89:22)
    at C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (C:\Users\jubij\AppData\Roaming\npm\node_modules\poosh-cli\node_modules\core-js\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

This is the file, which is looking very much like the exemple provided in the readme : 

``` json5
{
  plugins : ["poosh-plugin-s3"],
  baseDir : ".",
  remote  : "s3-website.eu-central-1.amazonaws.com/xxxxxxxxxxx",

  each: [{
    headers   : { "cache-control": { cacheable: "public" } }
  }, {
    match     : "**/*.{html,css,js}",
    gzip      : true,
    headers   : { "cache-control": { maxAge: "48 hours" } }
  }, {
    match     : "**/*.{jpg,png,gif,ico}",
    gzip      : false,
    headers   : { "cache-control": { maxAge: "6 months" } }
  }, {
    match     : "**/*.html",
    priority  : -1
  }]
}
```

I don't know AWS API so this may be normal, but this is at least a documentation bug.

**Comment by yvele** [comment]
Hi, this is not really a bug.
Poosh is using [ms.js](https://github.com/rauchg/ms.js) to parse durations.
And valid units are `years`, `days`, `hours`, `minutes`, `seconds`, `milliseconds`

I think month is not a valid unit because it doesn't have an official fixed duration, it can be 28, 29, 30 or 31 days..

There is an opened issue about the month unit here: https://github.com/rauchg/ms.js/issues/57 and I added a comment about month unit support.

**Comment by yvele** [comment]
Readme fixed: https://github.com/yvele/poosh/commit/7f6580d8a8e8cb2d473cc85bf429ec56731bea53

This was much more a documentation issue. I'm closing the issue as I fixed the readme.

PS: If you need 6 months, you can try `0.5 years` as a workaround :grin:
